### ISSUE TITLE
Can't render headers after they are sent to the client

### ISSUE THREAD

**Issue by nolanlawson** [gr2m/CORS-Proxy#25]
We see this bug all the time in PouchDB when we set this up as a proxy to CouchDB.  It's an intermittent in our unit tests:

```
http.js:731
    throw new Error('Can\'t render headers after they are sent to the client.'
    ^
Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (http.js:731:11)
    at ServerResponse.writeHead (http.js:1148:20)
    at ClientRequest.proxyError (/Users/nolan/workspace/pouchdb/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:213:9)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketOnData (http.js:1588:9)
    at TCP.onread (net.js:527:27)
```

Apparently it was fixed upstream (https://github.com/nodejitsu/node-http-proxy/pull/388), but this module still relies on an older version of http-proxy, so unfortunately we don't get the benefit.

I'm guessing this could be solved by updating it to work with http-proxy ^1.1.4?

**Comment by gr2m** [comment]
hey guys, I've redone `corsproxy`, no based on hapi. Let me know if you run into any problems
